eldorado:
  jwt:
    secret: KaPdRgUkXp2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D
    expirationMs: 1200000

management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always

  endpoints:
    web:
      exposure:
        include:
         - health
         - info
         - beans
         - env

spring:
  application:
    name: ms-autenticacao

eureka:
  client:
    service-url:
      defaultZone: http://${discovery_host:localhost}:8761/eureka